### ISSUE TITLE
FLAKY TEST: `noticeOfChangeOfAddressQCJourney.test.ts`

### ISSUE THREAD

**Issue by rachelschneiderman** [ustaxcourt/ef-cms#3986]
## Path to Test File
```
web-client/integration-tests/noticeOfChangeOfAddressQCJourney.test.ts
```

## Readout of the failure
![image](https://github.com/ustaxcourt/ef-cms/assets/20249233/d25a023a-ff39-4948-b151-10790de11d89)

Sometimes the failure occurs in the step `practitionerUpdatesAddress` in the last expectation (see below) because `state.alertSuccess` was undefined when that test step was executed.
```
expect(cerebralTest.getState('alertSuccess')).toMatchObject({
      message: 'Changes saved.',
    });
```

## What were you working on?

https://github.com/ustaxcourt/ef-cms/pull/3979

## Notes
- While debugging, we noticed in the GA runs the memory consumption in the container was nearing maximum available memory about 1/3 of the way through the test run and never really recovered.
- Also looks like the maximum wait (30,000 ms) is being reached when user contact edit is in progress.
![image](https://github.com/ustaxcourt/ef-cms/assets/20249233/165466b1-f5ce-49e9-98d4-cd6733b9ef19)

## Definition of Done (Updated 4-14-21)

**Engineering**

- [ ] Documentation has been added to this card with any helpful information relating to the test failures.
- [ ] Test has been fixed or removed.
- [ ] Test has been reattempted 5 times without fail.

**Comment by mmarcotte** [comment]
Observed on another [PR](https://github.com/ustaxcourt/ef-cms/pull/3983). [Failed action](https://github.com/ustaxcourt/ef-cms/actions/runs/6265603950/job/17015368321)

```
AIL web-client/integration-tests/noticeOfChangeOfAddressQCJourney.test.ts (473.761 s)
  ● Console

    console.log
      Waited 14000ms for the userContactEditProgress.inProgress to hide

      at log (integration-tests/helpers.ts:1035:11)

    console.log
      Waited 0ms for the progressIndicator.waitingForResponse to hide

      at log (integration-tests/helpers.ts:1035:11)

  ● noticeOfChangeOfAddressQCJourney › practitioner updates address

    thrown: "Exceeded timeout of 70000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      4 |
      5 | export const practitionerUpdatesAddress = cerebralTest => {
    > 6 |   return it('practitioner updates address', async () => {
        |          ^
      7 |     await cerebralTest.runSequence('gotoUserContactEditSequence');
      8 |
      9 |     await cerebralTest.runSequence('updateFormValueSequence', {

      at it (integration-tests/journey/practitionerUpdatesAddress.ts:6:10)
      at integration-tests/noticeOfChangeOfAddressQCJourney.test.ts:63:29
      at Object.describe (integration-tests/noticeOfChangeOfAddressQCJourney.test.ts:16:1)

  ● noticeOfChangeOfAddressQCJourney › Docket Clerk QCs NCA for case with paper service

    expect(received).toMatchObject(expected)

    Matcher error: received value must be a non-null object

    Received has value: undefined

      41 |     );
      42 |
    > 43 |     expect(noticeOfChangeOfAddressQCItem).toMatchObject({
         |                                           ^
      44 |       docketEntry: { documentTitle: 'Notice of Change of Address' },
      45 |     });
      46 |

      at toMatchObject (integration-tests/journey/docketClerkQCsNCAForCaseWithPaperService.ts:43:43)
      at call (integration-tests/journey/docketClerkQCsNCAForCaseWithPaperService.ts:2:1)
      at Generator.tryCatch (integration-tests/journey/docketClerkQCsNCAForCaseWithPaperService.ts:2:1)
      at Generator._invoke [as next] (integration-tests/journey/docketClerkQCsNCAForCaseWithPaperService.ts:2:1)
      at asyncGeneratorStep (integration-tests/journey/docketClerkQCsNCAForCaseWithPaperService.ts:2:1)
      at asyncGeneratorStep (integration-tests/journey/docketClerkQCsNCAForCaseWithPaperService.ts:2:1)
```

**Comment by ujahio** [comment]
Observed in this [PR](https://github.com/ustaxcourt/ef-cms/pull/3995) as well. Here's the [action](https://github.com/ustaxcourt/ef-cms/actions/runs/6300105797/job/17102194924?pr=3995)

<img width="1298" alt="Screenshot 2023-09-25 at 10 03 51 AM" src="https://github.com/ustaxcourt/ef-cms/assets/13560702/a0501fbc-74d9-4ead-ae04-8dc6569bb656">

**Comment by ujahio** [comment]
Findings:

We conducted an experiment to add privatePractitioner 2 to cases and the results are as follows:
1. private practitioner 2 - 65.927s, 60.372s, 59.462s
2. private practitioner - 78.802s, 76.104s, 76.637s
    
Based on the time difference, we have made the adjustments to use privatePractitioner2@example.com to reduce the time the test takes to run. Here's the PR: https://github.com/ustaxcourt/ef-cms/pull/4002
