### ISSUE TITLE
Debug IRS environment logs.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#607]
Look into issue as reported, starting Monday evening.

**Comment by adunkman** [comment]
Current status: waiting for more details.

**Comment by adunkman** [comment]
This appears to have been an issue with an expired token; interestingly, we do not have an expired token message coming from our authorizer. 

TODO: dig into where this token is rejected for being expired, and see why it isn’t in the logs.

**Comment by adunkman** [comment]
Confirmed that this should be happening in the Cognito authorizer, specifically when calling out to `jwt.verify` — [related documentation](https://github.com/auth0/node-jsonwebtoken/blob/master/README.md#jwtverifytoken-secretorpublickey-options-callback). We should expect to see `The token is not valid, considering request unauthorized` in the logs.

**Comment by adunkman** [comment]
We gained logging visibility into these errors in https://github.com/ustaxcourt/ef-cms/pull/572, which was deployed to the IRS test environment Nov 30 at 2:58 PM via https://github.com/ustaxcourt/ef-cms/pull/587. 

The "Monday evening" referenced above is Nov 30, so we should expect to see these logs in Kibana — but I do not (the authorizer logs are empty in the index). Continuing to dig!

**Comment by adunkman** [comment]
The first log entry to appear from `/aws/lambda/cognito_authorizer_lambda_irs` is on Dec 1 at 16:16:39.887, and is in the expected format from #572. 

Cloudwatch contains three log streams from Nov 30 (ET) which are in the expected format from #572 but do not appear in Kibana. 
  - 2020/12/01/[$LATEST]36db572362454022843347af407ca562
  - 2020/12/01/[$LATEST]c88d836cb5ed4e1ab04591535c96389a
  - 2020/12/01/[$LATEST]93e0a99593fc4af681339670b79ec420

They show the following requests:

- 2020/12/01/[$LATEST]36db572362454022843347af407ca562
  - 2020-11-30T20:33:03.513-05:00 (Nov 30, 8:33 PM): Authorization succeeded. (0a4f96e5-52d5-4f0f-ae14-225f515bee14)
  - 2020-11-30T20:38:54.657-05:00 (Nov 30, 8:38 PM): Authorization succeeded. (3cef19a7-697f-4f50-8148-81cc51cf07a3)
  - 2020-11-30T20:44:35.882-05:00 (Nov 30, 8:44 PM): Authorization succeeded. (b2e37822-f1db-48be-a16d-11d60691dbcd)
  - 2020-11-30T20:49:48.002-05:00 (Nov 30, 8:49 PM): Authorization succeeded. (ecdfb63d-250e-4866-b18d-9fa80e38ace5)
  - 2020-11-30T20:54:23.148-05:00 (Nov 30, 8:54 PM): Authorization succeeded. (400cfd98-c947-42be-901a-21061e99071a)

- 2020/12/01/[$LATEST]c88d836cb5ed4e1ab04591535c96389a
  - 2020-11-30T20:38:55.886-05:00 (Nov 30, 8:38 PM): Authorization succeeded. (f62e76a8-b45f-4c57-94a2-42577f6bc2c1)
  - 2020-11-30T20:44:35.793-05:00 (Nov 30, 8:44 PM): Authorization succeeded. (cf171231-b211-45af-a73e-ad4d00994341)
  - 2020-11-30T20:49:48.034-05:00 (Nov 30, 8:49 PM): Authorization succeeded. (a7a5150f-42e5-4301-98f6-f119b867ae43)
  - 2020-11-30T20:54:23.138-05:00 (Nov 30, 8:54 PM): Authorization succeeded. (bd657f16-378b-4255-87d4-18e16b76a6f1)

- 2020/12/01/[$LATEST]93e0a99593fc4af681339670b79ec420
  - 2020-11-30T21:07:39.875-05:00 (Nov 30, 9:07 PM): Authorization succeeded. (ebe1e1e7-80cc-4dfe-92ec-fb6a095cc0cc)

**Comment by adunkman** [comment]
Check for `logger.warn` vs `logger.warning` as Mark suggested.

**Comment by adunkman** [comment]
Confirmed that this is the issue!

<details>
<summary>Making a request as an expired token causes a 500 error.</summary>

```bash
➜ curl -H "Authorization: Bearer [REDACTED]" -v https://api-green.stg.ef-cms.ustaxcourt.gov/users
*   Trying 52.21.69.210...
* TCP_NODELAY set
* Connected to api-green.stg.ef-cms.ustaxcourt.gov (52.21.69.210) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=api-green.stg.ef-cms.ustaxcourt.gov
*  start date: Oct 15 00:00:00 2020 GMT
*  expire date: Nov 13 23:59:59 2021 GMT
*  subjectAltName: host "api-green.stg.ef-cms.ustaxcourt.gov" matched cert's "api-green.stg.ef-cms.ustaxcourt.gov"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7ff255008200)
> GET /users HTTP/2
> Host: api-green.stg.ef-cms.ustaxcourt.gov
> User-Agent: curl/7.64.1
> Accept: */*
> Authorization: Bearer [REDACTED]
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 500 
< date: Tue, 15 Dec 2020 21:03:14 GMT
< content-type: application/json
< content-length: 16
< x-amzn-requestid: 13c83952-fa67-492d-b1c1-da6b6dae0129
< x-amzn-errortype: AuthorizerConfigurationException
< x-amz-apigw-id: XnKmqHmcoAMFnYg=
< 
* Connection #0 to host api-green.stg.ef-cms.ustaxcourt.gov left intact
{"message":null}* Closing connection 0
```

</details>

<details>
<summary>Looking in the request logs, we can see "Execution failed due to an authorizer error"</summary>

```json
{
  "_index": "cwl-2020.12.15",
  "_type": "_doc",
  "_id": "35861074432085055682696054827448523768001170381176700928",
  "_version": 1,
  "_score": null,
  "_ignored": [
    "authorizer.responseTimeMs"
  ],
  "_source": {
    "authorizer": {
      "error": "Execution failed due to an authorizer error",
      "responseTimeMs": "-",
      "statusCode": "500"
    },
    "environment": {
      "color": "green",
      "stage": "stg"
    },
    "level": "info",
    "message": "API Gateway Access Log",
    "request": {
      "headers": {
        "user-agent": "curl/7.64.1",
        "x-forwarded-for": "73.200.234.126"
      },
      "method": "GET"
    },
    "requestId": {
      "apiGateway": "13c83952-fa67-492d-b1c1-da6b6dae0129",
      "authorizer": "399805ba-fb17-40d6-8ed9-ddb506d24f80",
      "lambda": "-"
    },
    "response": {
      "responseLength": "16",
      "responseTimeMs": "1530",
      "statusCode": "500"
    },
    "logGroup": "/aws/apigateway/gateway_api_stg_green",
    "logStream": "6afbb68a8c06cb72f96d4f81668418a2",
    "metadata": {
      "apiId": "nwey0mymyl",
      "resourceId": "blkrkw",
      "resourcePath": "/{proxy+}"
    },
    "timestamp": "2020-12-15T21:03:12.983Z"
  },
  "fields": {
    "timestamp": [
      "2020-12-15T21:03:12.983Z"
    ]
  },
  "highlight": {
    "requestId.apiGateway": [
      "@kibana-highlighted-field@13c83952-fa67-492d-b1c1-da6b6dae0129@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1608066192983
  ]
}
```
</details>

<details>
<summary>The crash appears in CloudWatch logs.</summary>

```json
{
    "errorType": "TypeError",
    "errorMessage": "logger.warn is not a function",
    "stack": [
        "TypeError: logger.warn is not a function",
        "    at Runtime.exports.handler (/var/task/cognito-authorizer.js:51235:12)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    ]
}
```
</details>

Next steps: 

- [x] Update tests to catch this situation
- [x] Fix `logger.warn` to `logger.warning`
- [ ] If possible, fix the unhandled exception logger to write in the expected log format to see these errors in Kibana.

**Comment by adunkman** [comment]
Confirmed fixed in staging: 

```json
{
  "_index": "cwl-2020.12.16",
  "_type": "_doc",
  "_id": "35863066134117887612767801465289476856032188630219882497",
  "_version": 1,
  "_score": null,
  "_source": {
    "environment": {
      "stage": "stg"
    },
    "requestId": {
      "authorizer": "8f040b5f-da99-478d-a14f-e8a0e4e193b5"
    },
    "message": "The token is not valid, considering request unauthorized jwt expired",
    "level": "warning",
    "logGroup": "/aws/lambda/cognito_authorizer_lambda_stg",
    "logStream": "2020/12/16/[$LATEST]4fe4072d0e994ff7b236b180eb4a3d14",
    "metadata": {
      "name": "TokenExpiredError",
      "expiredAt": "2020-12-15T17:27:46.000Z",
      "stack": "TokenExpiredError: jwt expired\n    at /var/task/cognito-authorizer.js:6177:21\n    at getSecret (/var/task/cognito-authorizer.js:6116:14)\n    at Object.module.exports [as verify] (/var/task/cognito-authorizer.js:6120:10)\n    at /var/task/cognito-authorizer.js:51187:9\n    at new Promise (<anonymous>)\n    at verify (/var/task/cognito-authorizer.js:51182:10)\n    at Runtime.exports.handler (/var/task/cognito-authorizer.js:51233:21)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    },
    "timestamp": "2020-12-16T21:51:43.991Z"
  },
  "fields": {
    "timestamp": [
      "2020-12-16T21:51:43.991Z"
    ]
  },
  "highlight": {
    "requestId.authorizer": [
      "@kibana-highlighted-field@8f040b5f-da99-478d-a14f-e8a0e4e193b5@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1608155503991
  ]
}
```
