### ISSUE TITLE
BUG: Practitioner cannot view some documents.

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#716]
**Describe the Bug**

It looks like users are getting unauthorized to view document for case documents even though they have access to it.  

```
Error: Unauthorized to view document at this time.
    at handleCourtIssued (/var/task/api.js:913128:11)
    at Object.exports.getDownloadPolicyUrlInteractor (/var/task/api.js:913228:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /var/task/api.js:1058811:10
    at async /var/task/api.js:1057709:23
    at async exports.handle (/var/task/api.js:1057484:20)
```

**Business Impact/Reason for Severity**

Petitioners and Practitioners should have access to all of the documents associated with their case (provided that it's not sealed)

**In which environment did you see this bug?**

Prod

**Who were you logged in as?**

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**

**Expected Behavior**

**Actual Behavior**
A clear and concise description of what actually happened.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by adunkman** [comment]
`POST` data would be very helpful in debugging this, since there’s lots of branching logic.
