### ISSUE TITLE
BUG: Unexpected log out during order drafting

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7629]
**Describe the Bug**
A Chambers Administrator was drafting a very long order and the system kicked her out without warning.  They lost a lot of work.  This seems to happen a lot when DAWSON opens a new window/tab.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's Prod

**Who were you logged in as?**
Angela Frith (Chambers Administrator)

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Working

**To Reproduce**

**Expected Behavior**
Remain logged in when drafting a long order

**Actual Behavior**
System logged her out without warning.  Does drafting an order count as "activity" to prevent log out due to inactivity?  We should ensure that the log-out warning is working everywhere.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. (sharing a token across multiple instances of the app can produce complexity; it's very hard to test 2 tabs with cypress; an oversight)
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss. (automated tests in cypress to cover this is very difficult, or might not be possible; we wrote a lot of unit tests for our changes)
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss. (probably not needed)
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented. (two instances of the app maintained their own idle status which produced conflicts; they were not synced up)
 - [x] Fix has been deployed to dev environment.
 - [x] Bug has been tested in dev (UX or Engineering).

**Comment by mariahkannenberg** [comment]
![image.png](https://images.zenhubusercontent.com/5bc501b8601657183131caf3/9c1a0f96-d29b-4fc2-a85f-b41ad075fad4)

**Comment by mariahkannenberg** [comment]
@mmarcotte Can you add logging to this one. See screenshot

**Comment by mariahkannenberg** [comment]
Questions:
* How do we reproduce?
* How do we know it's fixed?

**Comment by mmarcotte** [comment]
wonder if opening in a new tab doesn't have the same state that the previous tab (or the subsequent action taken in the new tab) relied upon 🤔

**Comment by mmarcotte** [comment]
Here's a tab-delimited server log of that user on that day. Note the one error they encountered @ 16:31:49.340:

```
Error: The Message entity was invalid. {"completedMessage":"'completedMessage' is not allowed to be empty"}
    at Proxy.validate (/var/task/api.js:808742:13)
    at Object.exports.completeMessageInteractor (/var/task/api.js:904657:46)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /var/task/api.js:1060508:10
    at async /var/task/api.js:1057709:23
    at async exports.handle (/var/task/api.js:1057484:20)
    at async /var/task/api.js:60372:22
```

[7401-server-log.zip](https://github.com/flexion/ef-cms/files/5882606/7401-server-log.zip)

**Comment by matthopson** [comment]
### Test Scenarios ###
*Assumes the default timeouts of:
  - 55 minutes until idle activity modal displays
  - 5 minutes after idle activity modal displays, the user is automatically logged out
  
#### Test that modal displays in the given timeout after no activity ####
 - Log in as an internal user
 - Open two more windows and place them side by side, ensuring you're logged into both and all three windows are visible.
 - Start a stopwatch and stay active in one of the tabs for two minutes
   - staying active means clicking around, navigation, typing, moving the mouse   
   - the reason for the stopwatch is to prove that the timeout shows in 55 minutes AFTER activity has ceased (this proves two or so minutes of activity was propagated across all tab instances)
 - Set an alarm / timer, etc... for 53 minutes
   -  The timer is to remind you to come back to the windows with time to visibly SEE the modals appear after the 55 minutes of inactivity, so the actual alarm time is up to you.
   - [x] The modal is displayed in ALL tabs / instances at the same time
   


 
 
 #### Test that the modal clears across all instances ####
 - With the "Are you still there?" modals displaying, click the "Yes!" button on ONE of them.
   - [x] The modals are dismissed across all other tabs / instances after clicking "Yes!"
 
 #### Test that the app logs out across all instances ####
- Set another timer for approx 55 minutes
- Grab some coffee
- Come back to tabs after timer
  - [x] Modals are displaying again
- Wait an additional 5 minutes
  - [x] 5 minutes after the modals displayed, all app instances were automatically logged out at the same time.

**Comment by sutt0n** [comment]
The broadcast channel flow designed (aided in solutioning) via https://draw.io:

![image](https://user-images.githubusercontent.com/1116426/107067030-55feee00-67a4-11eb-9ecc-8b7fe778e72c.png)
