### ISSUE TITLE
BUG: Do not persist PDF that fails validation

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7886]
**Describe the Bug**

External User, Petitioner, is reporting an "uh-oh" screen processing the PDF when trying to file an external document. The file remains in the documents bucket even though it fails validation. The PDF is not encrpyted.

Further investigation reveals that the PDF is created by PaperPort, which is an old Windows 7 piece of software. There is an [open issue out in pdf-js](https://github.com/Hopding/pdf-lib/issues/861) to address this particular error. 

However, the main issue is that we still persist the file after throwing the error.

**Business Impact/Reason for Severity**

We don't want to collect orphan PDFs that will never be used again.

**In which environment did you see this bug?**

Production

**Who were you logged in as?**

Petitioner

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Handling support ticket, reviewing server logs.

**To Reproduce**
1. Find the following PDF in the `mig` environment `2a9e4373-8891-41c3-b8b9-a0835f02880b`
2. Try to file it in any case.
3. Receive error
4. Observe error in logs: `Error: pdf pages cannot be read` 
5. Observe that the file is still persisted to the documents bucket

```
Error: pdf pages cannot be read
    at Object.exports.validatePdfInteractor (/var/task/api.js:7578:685)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /var/task/api.js:8298:161
    at async /var/task/api.js:7980:690
    at async exports.handle (/var/task/api.js:7978:1162)
    at async /var/task/api.js:468:932
```

**Expected Behavior**

If the PDF fails validation, we shouldn't persist the file.

**Actual Behavior**

PDF gets persisted. 

**Cause of Bug, If Known**

We explicitly remove files that fail encryption validation, but we do not for files that fail `getPages()` validation.

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by mmarcotte** [comment]
Looks like the PDF was created with PaperPort, and the user is using Windows 7. I mentioned this in an [existing issue on the pdf-js library](https://github.com/Hopding/pdf-lib/issues/861). Our hands might be tied here, and we won't be able to support this PDF with this library.

So, we may just need to make sure that we don't persist these file in S3 since it's now an unused orphan. And it really would be nice if we could give the user a message informing them that the PDF they are using is not serviceable.
