### ISSUE TITLE
BUG: Cannot enter a 2016 petition in PROD

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8321]
**Describe the Bug**
When attempting to enter a backdated 2016 petition in PROD, when clicking the Create Case button the user gets a "Try again/cancel" error message instead of the case being created. We have ensured the production counter is set correctly and been able to enter successfully on MIG and TEST.

The Kibana logs show the following error when the Create Case button is clicked:

ValidationException: An operand in the update expression has an incorrect data type
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18

**Business Impact/Reason for Severity**
While this functionality is not needed regularly, when it is needed it is usually urgent; in this case an innocent spouse severing her case from her spouse.

**In which environment did you see this bug?**
PROD

**Who were you logged in as?**

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**

**Expected Behavior**

**Actual Behavior**
A clear and concise description of what actually happened.
**Screenshots**

Data being entered in the petition creation:

{
   "petitionFileId":"568768ea-9b89-4423-bbd5-bb350f69de92",
   "petitionMetadata":{
      "contactPrimary":{
         "countryType":"domestic",
         "name":"Vicki Couturier",
         "address1":"12214 50th Ave. Ct.",
         "city":"Gig Harbor",
         "state":"WA",
         "postalCode":"98332-8861",
         "phone":"N/A"
      },
      "procedureType":"Regular",
      "hasVerifiedIrsNotice":false,
      "orderDesignatingPlaceOfTrial":true,
      "statistics":[
         
      ],
      "partyType":"Petitioner",
      "orderForOds":false,
      "caseCaption":"Vicki Couturier, Petitioner",
      "mailingDate":"Hand Delivered - FedEx",
      "petitionPaymentStatus":"Not paid",
      "orderForFilingFee":true,
      "petitionFile":{
         
      },
      "petitionFileSize":2872816,
      "receivedAt":"2016-09-07T04:00:00.000Z",
      "caseType":"Deficiency",
      "petitionPaymentDate":null,
      "petitionPaymentWaivedDate":null
   }
}

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by cholly75** [comment]
Docket counter had been set to String, changed it to Number type - clerk was able to successfully process backdated petition.
