### ISSUE TITLE
FLAKY TEST: Cypress Smoketests Local - Court Issued Documents

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#8498]
## Path to Test File

```
./cypress/cypress-smoketests/integration/court-issued-documents.cy.ts
```

## Readout of the failure

```
  Running:  court-issued-documents.cy.ts                                                    (3 of 6)


  Petitioner
    ✓ should be able to login (3785ms)
    should be able to create a case
      ✓ should complete wizard step 1 (388ms)
      ✓ should go to wizard step 2 (175ms)
      ✓ should complete the form and submit the petition (8901ms)

  Petitions clerk
    ✓ should be able to login (4417ms)
    ✓ should be able to create a case with paper service (16269ms)
    1) should be able to serve the petition on the electronically-filed case

  Docket Clerk
    ✓ should be able to login (4082ms)
    2) should be able to create an order on the electronically-filed case and serve it
    ✓ should be able to create an order on the paper-filed case and serve it (19550ms)
    ✓ should be able to upload a court-issued order pdf on the electronically-filed case (1976ms)
    ✓ should click the save uploaded PDF button (1085ms)
    3) should add a docket entry for the uploaded PDF and serve
    ✓ should be able to upload a court-issued order pdf on the paper-filed case (2428ms)
    ✓ should click the save uploaded PDF button (1039ms)
    ✓ should add a docket entry for the uploaded PDF and serve for paper (4429ms)


  13 passing (5m)
  3 failing

  1) Petitions clerk
       should be able to serve the petition on the electronically-filed case:
     AssertionError: Timed out retrying after 60000ms: Expected to find element: `a:contains("Review and Serve Petition")`, but never found it.
      at reviewAndServePetition (webpack://ef-cms/./cypress/cypress-smoketests/support/pages/case-detail.ts:120:0)
      at Context.eval (webpack://ef-cms/./cypress/cypress-smoketests/integration/court-issued-documents.cy.ts:71:0)

  2) Docket Clerk
       should be able to create an order on the electronically-filed case and serve it:
     AssertionError: Timed out retrying after 60000ms: Expected to find element: `button:contains("Serve")`, but never found it.
      at serveCourtIssuedDocketEntry (webpack://ef-cms/./cypress/cypress-smoketests/support/pages/case-detail.ts:64:0)
      at Context.eval (webpack://ef-cms/./cypress/cypress-smoketests/integration/court-issued-documents.cy.ts:92:0)

  3) Docket Clerk
       should add a docket entry for the uploaded PDF and serve:
     AssertionError: Timed out retrying after 60000ms: Expected to find element: `#serve-to-parties-btn`, but never found it.
      at addDocketEntryForUploadedPdfAndServe (webpack://ef-cms/./cypress/cypress-smoketests/support/pages/case-detail.ts:87:0)
      at Context.eval (webpack://ef-cms/./cypress/cypress-smoketests/integration/court-issued-documents.cy.ts:108:0)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        16                                                                               │
  │ Passing:      13                                                                               │
  │ Failing:      3                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  4                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     4 minutes, 30 seconds                                                            │
  │ Spec Ran:     court-issued-documents.cy.ts                                                     │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

## Workflows of Failrure(s)

https://github.com/ustaxcourt/ef-cms/actions/runs/5953526479/job/16147972417

## What were you working on?

Getting a PR into `staging`. Only change was to markdown

## Definition of Done (Updated 4-14-21)

**Engineering**

- [ ] Documentation has been added to this card with any helpful information relating to the test failures.
- [ ] Test has been fixed or removed.
- [ ] Test has been reattempted 5 times without fail.

**Comment by TomElliottFlexion** [comment]
Closing as this is a duplicate of https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/gh/flexion/ef-cms/10158
