### ISSUE TITLE
FLAKY TEST: `search.cy.ts` is failing intermittently

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#8500]
## Path to Test File

```
cypress/cypress-smoketests/integration/search.cy.ts
```

## Readout of the failure

```
Running:  search.cy.ts                                                                    (5 of 6)


  Create and serve a case to search for
    ✓ should be able to login (3933ms)
    ✓ should be able to create a case and serve to IRS (22635ms)

  Case Advanced Search
    ✓ should be able to login (3374ms)
    ✓ should be able to search for case by petitioner name (1456ms)
    ✓ should be able to search for case by docket number (833ms)

  Practitioner Search
    ✓ should be able to login (3651ms)
    ✓ should be able to search for a practitioner by name (1501ms)
    ✓ should be able to search for for a practitioner by bar number (862ms)

  Opinion Search
    ✓ should be able to login (3813ms)
    1) should create an opinion to search for
    2) should be able to search for an opinion by keyword


  9 passing (3m)
  2 failing

  1) Opinion Search
       should create an opinion to search for:
     AssertionError: Timed out retrying after 60000ms: Expected to find element: `div.document-viewer--documents-list:last-child`, but never found it.
      at addDocketEntryAndServeOpinion (webpack://ef-cms/./cypress/cypress-smoketests/support/pages/advanced-search.ts:77:0)
      at Context.eval (webpack://ef-cms/./cypress/cypress-smoketests/integration/search.cy.ts:95:0)

  2) Opinion Search
       should be able to search for an opinion by keyword:
     AssertionError: Timed out retrying after 60000ms: Expected to find element: `table.search-results`, but never found it.
      at searchOpinionByKeyword (webpack://ef-cms/./cypress/cypress-smoketests/support/pages/advanced-search.ts:64:0)
      at Context.eval (webpack://ef-cms/./cypress/cypress-smoketests/integration/search.cy.ts:100:0)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        11                                                                               │
  │ Passing:      9                                                                                │
  │ Failing:      2                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  2                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     2 minutes, 46 seconds                                                            │
  │ Spec Ran:     search.cy.ts                                                                     │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

```

## Workflows of Failure(s)

* https://github.com/ustaxcourt/ef-cms/actions/runs/5967110389/job/16188109901
* https://github.com/ustaxcourt/ef-cms/actions/runs/5967110389

## What were you working on?

Looking at failed actions :) 

## Notes

This seems similar to https://github.com/ustaxcourt/ef-cms/issues/3866

## Definition of Done (Updated 4-14-21)

**Engineering**

- [x] Documentation has been added to this card with any helpful information relating to the test failures.
- [x] Test has been fixed or removed.
- [x] Test has been reattempted 5 times without fail.

**Comment by mmarcotte** [comment]
Looks like a similar issue as [USTC-3866](https://github.com/ustaxcourt/ef-cms/issues/3866). 

A click was failing for no good reason right after attaching a pdf to a file input. So, the PDF was never fully uploaded, and the whole test was pretty much broken from that point on. 

We are attempting to employ the same fix that got 3866 to work -- simply adding a `cy.wait(0);` before the click.
